apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "TestAPP"
  links:
    - url: https://google.com
      title: My Dashboard
      icon: dashboard
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
